-- Recomendado caso já exista alguma tabela com o mesmo nome

DROP TABLE ODONTO_SINISTRO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PROCEDIMENTO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_CLINICA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_DENTISTA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PLANO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_SCORING CASCADE CONSTRAINTS;


-- Tabela ODONTO_ENDERECO
CREATE TABLE ODONTO_ENDERECO (
    ID_ENDERECO NUMERIC(10) PRIMARY KEY,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

SELECT * FROM ODONTO_ENDERECO;

-- Tabela ODONTO_PLANO
CREATE TABLE ODONTO_PLANO (
    ID_PLANO NUMERIC(10) PRIMARY KEY,
    NOME_PLANO VARCHAR(100) NOT NULL,
    TIPO_PLANO VARCHAR(50) NOT NULL,
    VALOR_PLANO NUMERIC(10, 2) NOT NULL
);

SELECT * FROM ODONTO_PLANO;

-- Tabela ODONTO_PACIENTE
CREATE TABLE ODONTO_PACIENTE (
    ID_PACIENTE NUMERIC(10) PRIMARY KEY,
    NOME_PACIENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO_PACIENTE DATE NOT NULL,
    SEXO_PACIENTE VARCHAR(1) NOT NULL,
    CPF_PACIENTE VARCHAR(14)NOT NULL,
    EMAIL_PACIENTE VARCHAR(100),
    TELEFONE_PACIENTE VARCHAR(15) NOT NULL,
    HISTORICO_ODONTOLOGICO VARCHAR(2000),
    FREQUENCIA_CONSULTAS NUMERIC(10) DEFAULT 0,
    ID_ENDERECO NUMERIC(10),
    ID_PLANO NUMERIC(10),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_PLANO) REFERENCES ODONTO_PLANO(ID_PLANO)
);

SELECT * FROM ODONTO_PACIENTE;

-- Tabela ODONTO_DENTISTA
CREATE TABLE ODONTO_DENTISTA (
    ID_DENTISTA NUMERIC(10) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    CRO VARCHAR(15) NOT NULL,
    TAXA_SINISTROS NUMERIC(5, 2) DEFAULT 0,
    ID_ENDERECO NUMERIC(10),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO)
);

SELECT * FROM ODONTO_DENTISTA;

-- Tabela ODONTO_CLINICA
CREATE TABLE ODONTO_CLINICA (
    ID_CLINICA NUMERIC(10) PRIMARY KEY,
    NOME_CLINICA VARCHAR(100) NOT NULL,
    TIPO_ATENDIMENTO VARCHAR(50) NOT NULL,
    ID_ENDERECO NUMERIC(10),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO)
);

SELECT * FROM ODONTO_CLINICA;

-- Tabela ODONTO_CONSULTA
CREATE TABLE ODONTO_CONSULTA (
    ID_CONSULTA NUMERIC(10) PRIMARY KEY,
    DATA_CONSULTA DATE NOT NULL,
    HORA_CONSULTA VARCHAR(5) NOT NULL,
    MOTIVO_CONSULTA VARCHAR(255) NOT NULL,
    TIPO_CONSULTA VARCHAR(50) NOT NULL,
    STATUS_CONSULTA VARCHAR(20) DEFAULT 'Realizada',
    TEMPO_MEDIO_ESPERA NUMERIC(10, 2),
    ID_PACIENTE NUMERIC(10) NOT NULL,
    ID_DENTISTA NUMERIC(10) NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES ODONTO_PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_DENTISTA) REFERENCES ODONTO_DENTISTA(ID_DENTISTA)
);

SELECT * FROM ODONTO_CONSULTA;

-- Tabela ODONTO_PROCEDIMENTO
CREATE TABLE ODONTO_PROCEDIMENTO (
    ID_PROCEDIMENTO NUMERIC(10) PRIMARY KEY,
    TIPO_PROCEDIMENTO VARCHAR(100) NOT NULL,
    CUSTO_PROCEDIMENTO NUMERIC(10, 2) NOT NULL,
    ID_CONSULTA NUMERIC(10) NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES ODONTO_CONSULTA(ID_CONSULTA)
);

SELECT * FROM ODONTO_PROCEDIMENTO;

-- Tabela ODONTO_SINISTRO
CREATE TABLE ODONTO_SINISTRO (
    ID_SINISTRO NUMERIC(10) PRIMARY KEY,
    DATA_SINISTRO DATE NOT NULL,
    VALOR_SINISTRO NUMERIC(10, 2) NOT NULL,
    ID_CONSULTA NUMERIC(10) NOT NULL,
    CAUSA_SINISTRO VARCHAR(255),
    STATUS_SINISTRO VARCHAR(20) DEFAULT 'Aberto',
    FOREIGN KEY (ID_CONSULTA) REFERENCES ODONTO_CONSULTA(ID_CONSULTA)
);

SELECT * FROM ODONTO_SINISTRO;

-- Tabela ODONTO_SCORING
CREATE TABLE ODONTO_SCORING (
    ID_SCORING NUMBER(10) PRIMARY KEY,
    ID_DENTISTA NUMBER(10) NOT NULL,
    SCORING NUMBER(5, 2) NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    FOREIGN KEY (ID_DENTISTA) REFERENCES ODONTO_DENTISTA(ID_DENTISTA)
);

SELECT * FROM ODONTO_SCORING;
